export const deepArrayObject = [
    {
      test: [
        {
          test: [
            { tes: "test 1" },
            { tes: "test 2" },
            { tes: "test 3" },
            { tes: "test 4" },
            { tes: "test 5" },
            { tes: "test 6" },
            { tes: "test 7" },
            { tes: "test 8" },
            { tes: "test 9" },
            { tes: "test 0" },
          ],
        },
        {
          test: [
            { tes: "test 11" },
            { tes: "test 12" },
            { tes: "test 13" },
            { tes: "test 14" },
            { tes: "test 15" },
            { tes: "test 16" },
            { tes: "test 17" },
            { tes: "test 18" },
            { tes: "test 19" },
            { tes: "test 20" },
          ],
        },
        {
          test: [
            { tes: "test 31" },
            { tes: "test 32" },
            { tes: "test 33" },
            { tes: "test 34" },
            { tes: "test 35" },
            { tes: "test 36" },
            { tes: "test 37" },
            { tes: "test 38" },
            { tes: "test 39" },
            { tes: "test 40" },
          ],
        },
        {
          test: [
            { tes: "test 41" },
            { tes: "test 42" },
            { tes: "test 43" },
            { tes: "test 44" },
            { tes: "test 45" },
            { tes: "test 46" },
            { tes: "test 47" },
            { tes: "test 48" },
            { tes: "test 49" },
            { tes: "test 50" },
          ],
        },
      ],
    },
    {
      test: [
        {
          test: [
            { tes: "test 51" },
            { tes: "test 52" },
            { tes: "test 53" },
            { tes: "test 54" },
            { tes: "test 55" },
            { tes: "test 56" },
            { tes: "test 57" },
            { tes: "test 58" },
            { tes: "test 59" },
            { tes: "test 60" },
          ],
        },
        {
          test: [
            { tes: "test 61" },
            { tes: "test 62" },
            { tes: "test 63" },
            { tes: "test 64" },
            { tes: "test 65" },
            { tes: "test 66" },
            { tes: "test 67" },
            { tes: "test 68" },
            { tes: "test 69" },
            { tes: "test 70" },
          ],
        },
        {
          test: [
            { tes: "test 71" },
            { tes: "test 72" },
            { tes: "test 73" },
            { tes: "test 74" },
            { tes: "test 75" },
            { tes: "test 76" },
            { tes: "test 77" },
            { tes: "test 78" },
            { tes: "test 79" },
            { tes: "test 80" },
          ],
        },
        {
          test: [
            { tes: "test 81" },
            { tes: "test 82" },
            { tes: "test 83" },
            { tes: "test 84" },
            { tes: "test 85" },
            { tes: "test 86" },
            { tes: "test 87" },
            { tes: "test 88" },
            { tes: "test 89" },
            { tes: "test 90" },
          ],
        },
      ],
    },
    {
      test: [
        {
          test: [
            { tes: "test 91" },
            { tes: "test 92" },
            { tes: "test 93" },
            { tes: "test 94" },
            { tes: "test 95" },
            { tes: "test 96" },
            { tes: "test 97" },
            { tes: "test 98" },
            { tes: "test 99" },
            { tes: "test 100" },
          ],
        },
        {
          test: [
            { tes: "test 101" },
            { tes: "test 102" },
            { tes: "test 103" },
            { tes: "test 104" },
            { tes: "test 105" },
            { tes: "test 106" },
            { tes: "test 107" },
            { tes: "test 108" },
            { tes: "test 109" },
            { tes: "test 110" },
          ],
        },
        {
          test: [
            { tes: "test 111" },
            { tes: "test 112" },
            { tes: "test 113" },
            { tes: "test 114" },
            { tes: "test 115" },
            { tes: "test 116" },
            { tes: "test 117" },
            { tes: "test 118" },
            { tes: "test 119" },
            { tes: "test 120" },
          ],
        },
        {
          test: [
            { tes: "test 121" },
            { tes: "test 122" },
            { tes: "test 123" },
            { tes: "test 124" },
            { tes: "test 125" },
            { tes: "test 126" },
            { tes: "test 127" },
            { tes: "test 128" },
            { tes: "test 129" },
            { tes: "test 130" },
          ],
        },
      ],
    },
    {
      test: [
        {
          test: [
            { tes: "test 131" },
            { tes: "test 132" },
            { tes: "test 133" },
            { tes: "test 134" },
            { tes: "test 135" },
            { tes: "test 136" },
            { tes: "test 137" },
            { tes: "test 138" },
            { tes: "test 139" },
            { tes: "test 140" },
          ],
        },
        {
          test: [
            { tes: "test 141" },
            { tes: "test 142" },
            { tes: "test 143" },
            { tes: "test 144" },
            { tes: "test 145" },
            { tes: "test 146" },
            { tes: "test 147" },
            { tes: "test 148" },
            { tes: "test 149" },
            { tes: "test 150" },
          ],
        },
        {
          test: [
            { tes: "test 151" },
            { tes: "test 152" },
            { tes: "test 153" },
            { tes: "test 154" },
            { tes: "test 155" },
            { tes: "test 156" },
            { tes: "test 157" },
            { tes: "test 158" },
            { tes: "test 159" },
            { tes: "test 160" },
          ],
        },
        {
          test: [
            { tes: "test 161" },
            { tes: "test 162" },
            { tes: "test 163" },
            { tes: "test 164" },
            { tes: "test 165" },
            { tes: "test 166" },
            { tes: "test 167" },
            { tes: "test 168" },
            { tes: "test 169" },
            { tes: "test 170" },
          ],
        },
      ],
    },
    {
      test: [
        {
          test: [
            { tes: "test 171" },
            { tes: "test 172" },
            { tes: "test 173" },
            { tes: "test 174" },
            { tes: "test 175" },
            { tes: "test 176" },
            { tes: "test 177" },
            { tes: "test 178" },
            { tes: "test 179" },
            { tes: "test 180" },
          ],
        },
        {
          test: [
            { tes: "test 181" },
            { tes: "test 182" },
            { tes: "test 183" },
            { tes: "test 184" },
            { tes: "test 185" },
            { tes: "test 186" },
            { tes: "test 187" },
            { tes: "test 188" },
            { tes: "test 189" },
            { tes: "test 190" },
          ],
        },
        {
          test: [
            { tes: "test 191" },
            { tes: "test 192" },
            { tes: "test 193" },
            { tes: "test 194" },
            { tes: "test 195" },
            { tes: "test 196" },
            { tes: "test 197" },
            { tes: "test 198" },
            { tes: "test 199" },
            { tes: "test 200" },
          ],
        },
        {
          test: [
            { tes: "test 201" },
            { tes: "test 202" },
            { tes: "test 203" },
            { tes: "test 204" },
            { tes: "test 205" },
            { tes: "test 206" },
            { tes: "test 207" },
            { tes: "test 208" },
            { tes: "test 209" },
            { tes: "test 210" },
          ],
        },
      ],
    },
  ];

  export const arrayObject = [
    { tes: "test 1" },
    { tes: "test 2" },
    { tes: "test 3" },
    { tes: "test 4" },
    { tes: "test 5" },
    { tes: "test 6" },
    { tes: "test 7" },
    { tes: "test 8" },
    { tes: "test 9" },
    { tes: "test 10" }
]

export const notArrayObject = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10
]

export const deepObject =  {
  one: [
    { tes: "test 21" },
    { tes: "test 22" },
    { tes: "test 23" },
    { tes: "test 24" },
    { tes: "test 25" },
    { tes: "test 26" },
    { tes: "test 27" },
    { tes: "test 28" },
    { tes: "test 29" },
    { tes: [
      { tes: "test 1" },
      { tes: "test 2" },
      { tes: "test 3" },
      { tes: "test 4" },
      { tes: "test 5" },
      { tes: "test 6" },
      { tes: "test 7" },
      { tes: "test 8" },
      { tes: "test 9" },
      { tes: "test 10" }
    ] },
  ],
  two: [
    { tes: "test 31" },
    { tes: "test 32" },
    { tes: "test 33" },
    { tes: "test 34" },
    { tes: "test 35" },
    { tes: "test 36" },
    { tes: "test 37" },
    { tes: "test 38" },
    { tes: "test 39" },
    { tes: [
      { tes: "test 11" },
      { tes: "test 12" },
      { tes: "test 13" },
      { tes: "test 14" },
      { tes: "test 15" },
      { tes: "test 16" },
      { tes: "test 17" },
      { tes: "test 18" },
      { tes: "test 19" },
      { tes: "test 20" }
    ] },
  ],
  three: [
    { tes: "test 41" },
    { tes: "test 42" },
    { tes: "test 43" },
    { tes: "test 44" },
    { tes: "test 45" },
    { tes: "test 46" },
    { tes: "test 47" },
    { tes: "test 48" },
    { tes: "test 49" },
    { tes: [
      { tes: "test 31" },
      { tes: "test 32" },
      { tes: "test 33" },
      { tes: "test 34" },
      { tes: "test 35" },
      { tes: "test 36" },
      { tes: "test 37" },
      { tes: "test 38" },
      { tes: "test 39" },
      { tes: "test 40" }
    ] },
  ],
};

export const object = {
  a: "test 21",
  b: "test 22",
  c: "test 23",
  d: "test 24",
  e: "test 25",
  f: "test 26",
  g: "test 27",
  h: "test 28",
  i: "test 29",
  j: "test 30",
}

export const mixedArray = [...deepArrayObject, ...arrayObject, ...notArrayObject]
export const mixedObject = { ...deepObject, ...object }

